# Generated by dev/probe_ml.exs against a live Spark 4.2.0 server. Do not hand-edit.
#
# What the server accepted and answered, operator by operator. `Latu.ML.Registry` reads this
# and it is where every constructor's status line comes from; delete it and everything falls
# back to `:built`, which is what a package with no probe result is entitled to claim.
#
#     mix run dev/probe_ml.exs -- --write
#
# A `:built` reason is far more often this fixture being the wrong shape for the operator
# than the operator being broken. Read dev/probe_ml.exs's own table first.
%{
  spark: "4.2.0",
  operators: %{
    aft_survival_regression: %{
      status: :probed,
      reason: nil,
      attributes: [coefficients: :ok, intercept: :ok, num_features: :ok, scale: :ok]
    },
    als: %{
      status: :probed,
      reason: nil,
      attributes: [item_factors: :ok, rank: :ok, user_factors: :ok]
    },
    binarizer: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    binary_classification_evaluator: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    bisecting_k_means: %{
      status: :probed,
      reason: nil,
      attributes: [cluster_center_matrix: :ok, has_summary: :ok, num_features: :ok, "summary.cluster": :ok, "summary.cluster_sizes": :ok, "summary.features_col": :ok, "summary.k": :ok, "summary.num_iter": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.training_cost": :ok]
    },
    bucketed_random_projection_lsh: %{
      status: :probed,
      reason: nil,
      attributes: []
    },
    bucketizer: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    chi_sq_selector: %{
      status: :probed,
      reason: nil,
      attributes: [selected_features: :ok]
    },
    clustering_evaluator: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    count_vectorizer: %{
      status: :probed,
      reason: nil,
      attributes: [vocabulary: :ok]
    },
    dct: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    decision_tree_classifier: %{
      status: :probed,
      reason: nil,
      attributes: [depth: :ok, feature_importances: :ok, num_classes: :ok, num_features: :ok, num_nodes: :ok, to_debug_string: :ok]
    },
    decision_tree_regressor: %{
      status: :probed,
      reason: nil,
      attributes: [depth: :ok, feature_importances: :ok, num_features: :ok, num_nodes: :ok, to_debug_string: :ok]
    },
    elementwise_product: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    feature_hasher: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    fm_classifier: %{
      status: :probed,
      reason: nil,
      attributes: [factors: :ok, has_summary: :ok, intercept: :ok, linear: :ok, num_classes: :ok, num_features: :ok, "summary.accuracy": :ok, "summary.area_under_roc": :ok, "summary.f_measure_by_threshold": :ok, "summary.false_positive_rate_by_label": :ok, "summary.label_col": :ok, "summary.labels": :ok, "summary.objective_history": :ok, "summary.pr": :ok, "summary.precision_by_label": :ok, "summary.precision_by_threshold": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.recall_by_label": :ok, "summary.recall_by_threshold": :ok, "summary.roc": :ok, "summary.score_col": :ok, "summary.total_iterations": :ok, "summary.true_positive_rate_by_label": :ok, "summary.weight_col": :ok, "summary.weighted_false_positive_rate": :ok, "summary.weighted_precision": :ok, "summary.weighted_recall": :ok, "summary.weighted_true_positive_rate": :ok]
    },
    fm_regressor: %{
      status: :probed,
      reason: nil,
      attributes: [factors: :ok, intercept: :ok, linear: :ok, num_features: :ok]
    },
    fp_growth: %{
      status: :probed,
      reason: nil,
      attributes: [association_rules: :ok, freq_itemsets: :ok]
    },
    gaussian_mixture: %{
      status: :probed,
      reason: nil,
      attributes: [gaussians_df: :ok, has_summary: :ok, num_features: :ok, "summary.cluster": :ok, "summary.cluster_sizes": :ok, "summary.features_col": :ok, "summary.k": :ok, "summary.log_likelihood": :ok, "summary.num_iter": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.probability": :ok, "summary.probability_col": :ok, weights: :ok]
    },
    gbt_classifier: %{
      status: :probed,
      reason: nil,
      attributes: [feature_importances: :ok, get_num_trees: :ok, num_classes: :ok, num_features: :ok, to_debug_string: :ok, total_num_nodes: :ok, tree_weights: :ok]
    },
    gbt_regressor: %{
      status: :probed,
      reason: nil,
      attributes: [feature_importances: :ok, get_num_trees: :ok, num_features: :ok, to_debug_string: :ok, total_num_nodes: :ok, tree_weights: :ok]
    },
    generalized_linear_regression: %{
      status: :probed,
      reason: nil,
      attributes: [coefficients: :ok, has_summary: :ok, intercept: :ok, num_features: :ok, "summary.aic": :ok, "summary.coefficient_standard_errors": :ok, "summary.degrees_of_freedom": :ok, "summary.deviance": :ok, "summary.dispersion": :ok, "summary.null_deviance": :ok, "summary.num_instances": :ok, "summary.num_iterations": :ok, "summary.p_values": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.rank": :ok, "summary.residual_degree_of_freedom": :ok, "summary.residual_degree_of_freedom_null": :ok, "summary.solver": :ok, "summary.t_values": :ok, "summary.to_string": :ok]
    },
    hashing_tf: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    idf: %{
      status: :probed,
      reason: nil,
      attributes: [doc_freq: :ok, idf: :ok, num_docs: :ok]
    },
    imputer: %{
      status: :probed,
      reason: nil,
      attributes: [surrogate_df: :ok]
    },
    index_to_string: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    interaction: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    isotonic_regression: %{
      status: :probed,
      reason: nil,
      attributes: [boundaries: :ok, num_features: :ok, predictions: :ok]
    },
    k_means: %{
      status: :probed,
      reason: nil,
      attributes: [cluster_center_matrix: :ok, has_summary: :ok, num_features: :ok, "summary.cluster": :ok, "summary.cluster_sizes": :ok, "summary.features_col": :ok, "summary.k": :ok, "summary.num_iter": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.training_cost": :ok]
    },
    lda: %{
      status: :probed,
      reason: nil,
      attributes: [estimated_doc_concentration: :ok, is_distributed: :ok, topics_matrix: :ok, vocab_size: :ok]
    },
    linear_regression: %{
      status: :probed,
      reason: nil,
      attributes: [coefficients: :ok, has_summary: :ok, intercept: :ok, num_features: :ok, scale: :ok, "summary.coefficient_standard_errors": :ok, "summary.degrees_of_freedom": :ok, "summary.deviance_residuals": :ok, "summary.explained_variance": :ok, "summary.features_col": :ok, "summary.label_col": :ok, "summary.mean_absolute_error": :ok, "summary.mean_squared_error": :ok, "summary.num_instances": :ok, "summary.objective_history": :ok, "summary.p_values": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.r2": :ok, "summary.r2adj": :ok, "summary.residuals": :ok, "summary.root_mean_squared_error": :ok, "summary.t_values": :ok, "summary.total_iterations": :ok]
    },
    linear_svc: %{
      status: :probed,
      reason: nil,
      attributes: [coefficients: :ok, has_summary: :ok, intercept: :ok, num_classes: :ok, num_features: :ok, "summary.accuracy": :ok, "summary.area_under_roc": :ok, "summary.f_measure_by_threshold": :ok, "summary.false_positive_rate_by_label": :ok, "summary.label_col": :ok, "summary.labels": :ok, "summary.objective_history": :ok, "summary.pr": :ok, "summary.precision_by_label": :ok, "summary.precision_by_threshold": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.recall_by_label": :ok, "summary.recall_by_threshold": :ok, "summary.roc": :ok, "summary.score_col": :ok, "summary.total_iterations": :ok, "summary.true_positive_rate_by_label": :ok, "summary.weight_col": :ok, "summary.weighted_false_positive_rate": :ok, "summary.weighted_precision": :ok, "summary.weighted_recall": :ok, "summary.weighted_true_positive_rate": :ok]
    },
    logistic_regression: %{
      status: :probed,
      reason: nil,
      attributes: [coefficient_matrix: :ok, coefficients: :ok, has_summary: :ok, intercept: :ok, intercept_vector: :ok, num_classes: :ok, num_features: :ok, "summary.accuracy": :ok, "summary.false_positive_rate_by_label": :ok, "summary.features_col": :ok, "summary.label_col": :ok, "summary.labels": :ok, "summary.objective_history": :ok, "summary.precision_by_label": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.probability_col": :ok, "summary.recall_by_label": :ok, "summary.total_iterations": :ok, "summary.true_positive_rate_by_label": :ok, "summary.weight_col": :ok, "summary.weighted_false_positive_rate": :ok, "summary.weighted_precision": :ok, "summary.weighted_recall": :ok, "summary.weighted_true_positive_rate": :ok]
    },
    max_abs_scaler: %{
      status: :probed,
      reason: nil,
      attributes: [max_abs: :ok]
    },
    min_hash_lsh: %{
      status: :probed,
      reason: nil,
      attributes: []
    },
    min_max_scaler: %{
      status: :probed,
      reason: nil,
      attributes: [original_max: :ok, original_min: :ok]
    },
    multiclass_classification_evaluator: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    multilabel_classification_evaluator: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    multilayer_perceptron_classifier: %{
      status: :probed,
      reason: nil,
      attributes: [has_summary: :ok, num_classes: :ok, num_features: :ok, "summary.accuracy": :ok, "summary.false_positive_rate_by_label": :ok, "summary.label_col": :ok, "summary.labels": :ok, "summary.objective_history": :ok, "summary.precision_by_label": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.recall_by_label": :ok, "summary.total_iterations": :ok, "summary.true_positive_rate_by_label": :ok, "summary.weight_col": :ok, "summary.weighted_false_positive_rate": :ok, "summary.weighted_precision": :ok, "summary.weighted_recall": :ok, "summary.weighted_true_positive_rate": :ok, weights: :ok]
    },
    naive_bayes: %{
      status: :probed,
      reason: nil,
      attributes: [num_classes: :ok, num_features: :ok, pi: :ok, sigma: :ok, theta: :ok]
    },
    ngram: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    normalizer: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    one_hot_encoder: %{
      status: :probed,
      reason: nil,
      attributes: [category_sizes: :ok]
    },
    pca: %{
      status: :probed,
      reason: nil,
      attributes: [explained_variance: :ok, pc: :ok]
    },
    polynomial_expansion: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    quantile_discretizer: %{
      status: :probed,
      reason: nil,
      attributes: []
    },
    r_formula: %{
      status: :probed,
      reason: nil,
      attributes: [resolved_formula_string: :ok]
    },
    random_forest_classifier: %{
      status: :probed,
      reason: nil,
      attributes: [feature_importances: :ok, get_num_trees: :ok, has_summary: :ok, num_classes: :ok, num_features: :ok, "summary.accuracy": :ok, "summary.false_positive_rate_by_label": :ok, "summary.label_col": :ok, "summary.labels": :ok, "summary.objective_history": :ok, "summary.precision_by_label": :ok, "summary.prediction_col": :ok, "summary.predictions": :ok, "summary.recall_by_label": :ok, "summary.total_iterations": :ok, "summary.true_positive_rate_by_label": :ok, "summary.weight_col": :ok, "summary.weighted_false_positive_rate": :ok, "summary.weighted_precision": :ok, "summary.weighted_recall": :ok, "summary.weighted_true_positive_rate": :ok, to_debug_string: :ok, total_num_nodes: :ok, tree_weights: :ok]
    },
    random_forest_regressor: %{
      status: :probed,
      reason: nil,
      attributes: [feature_importances: :ok, get_num_trees: :ok, num_features: :ok, to_debug_string: :ok, total_num_nodes: :ok, tree_weights: :ok]
    },
    ranking_evaluator: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    regex_tokenizer: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    regression_evaluator: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    robust_scaler: %{
      status: :probed,
      reason: nil,
      attributes: [median: :ok, range: :ok]
    },
    sql_transformer: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    standard_scaler: %{
      status: :probed,
      reason: nil,
      attributes: [mean: :ok, std: :ok]
    },
    stop_words_remover: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    string_indexer: %{
      status: :probed,
      reason: nil,
      attributes: [labels: :ok, labels_array: :ok]
    },
    target_encoder: %{
      status: :probed,
      reason: nil,
      attributes: []
    },
    tokenizer: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    univariate_feature_selector: %{
      status: :probed,
      reason: nil,
      attributes: [selected_features: :ok]
    },
    variance_threshold_selector: %{
      status: :probed,
      reason: nil,
      attributes: [selected_features: :ok]
    },
    vector_assembler: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    vector_indexer: %{
      status: :probed,
      reason: nil,
      attributes: [category_maps_df: :ok, num_features: :ok]
    },
    vector_size_hint: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    vector_slicer: %{
      status: :probed,
      reason: nil,
      attributes: %{}
    },
    word2vec: %{
      status: :probed,
      reason: nil,
      attributes: [get_vectors: :ok]
    }
  }
}
