defmodule Latu.ML.Wire do
  @moduledoc false
  # Golden protos, generated by `python dev/pyspark_oracle.py --generate`. Loaded by
  # test_helper.exs, so it stays out of the compiled application.
  #
  # Latu's `test/support/wire.exs`, narrowed. The normaliser is Latu's own
  # `Latu.Plan.normalize_ids/1` — the same one the oracle mirrors — so there is one rule here
  # and not a third copy of it.

  import ExUnit.Assertions

  alias Latu.DataFrame
  alias Latu.Plan
  alias Latu.Protocol.Spark.Connect, as: Proto

  @dir "test/wire"

  # Pinned in dev/pyspark_oracle.py. PySpark and Latu ML both generate a random uid per
  # operator, so a fixture can have neither.
  def assembler_uid, do: "latu_ml_fixture_assembler"
  def estimator_uid, do: "latu_ml_fixture_estimator"
  def evaluator_uid, do: "latu_ml_fixture_evaluator"
  def model_ref, do: "latu_ml_fixture_model"

  @doc """
  The uid a helper-built model carries.

  Pinned in the oracle by holding `Identifiable._randomUID` still: a model a classmethod builds
  generates its own uid inside the call, out of reach of the `_resetUid` every other fixture
  uses.
  """
  def helper_uid, do: "latu_ml_fixture_helper"

  @doc "Where the persistence fixtures write to and read from. Nothing is ever at it."
  def save_path, do: "/tmp/latu_ml_fixture/saved"

  @doc "The one base frame every fixture is built on, with no session behind it."
  def base, do: %DataFrame{session: nil, plan: Plan.range(0, 4, 1)}

  @doc "Assert a lazy frame is the relation PySpark builds. Returns its argument, so it chains."
  def assert_wire(%DataFrame{} = df, name) do
    assert_wire(df.plan, name)
    df
  end

  def assert_wire(%Proto.Relation{} = relation, name) do
    assert relation |> Plan.normalize_ids() |> Plan.new() == expected(name)
    relation
  end

  @doc "Assert a command plan is the one PySpark builds — a `Fit`, a `Fetch`, a `Delete`."
  def assert_wire_command(%Proto.Plan{} = plan, name) do
    assert Plan.normalize_ids(plan) == expected(name)
    plan
  end

  @doc """
  Assert a message that is not a plan — a `Literal` out of `Latu.ML.Linalg`.

  Decodes with the message's own module, so the fixture and the value have to be the same
  message; a fixture written from a different one fails to decode rather than comparing false.
  """
  def assert_wire_message(%module{} = message, name) do
    assert Plan.normalize_ids(message) == module.decode(read(name))
    message
  end

  defp expected(name), do: Proto.Plan.decode(read(name))

  defp read(name) do
    path = Path.join(@dir, "#{name}.bin")

    case File.read(path) do
      {:ok, bytes} ->
        bytes

      {:error, :enoent} ->
        flunk("""
        no fixture at #{path}.

        Fixtures are generated, not written by hand:

            export SPARK_REMOTE='sc://localhost:15003'
            python dev/pyspark_oracle.py --generate

        Run it twice; the second run must leave the tree clean.
        """)
    end
  end
end
